// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mutbstczflzfzddngzfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11dGJzdGN6Zmx6ZnpkZG5nemZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODg1NDMsImV4cCI6MjA2MTM2NDU0M30.w9L_jzIWfwWoiQWYnUb4Qch7A4SsFp_4858GeqW8k6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);